spring:
  datasource:
    password: Root@123
    url: jdbc:mysql://localhost:3306/new_workout_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
